amcl:
  ros__parameters:
    use_sim_time: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    scan_topic: "scan"
    map_topic: "map"
    max_particles: 5000

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: ""  #EN principio puede estar vacio, porque le paso la ruta en navigation.launch.py

map_saver:
  ros__parameters:
    use_sim_time: true
    save_map_timeout: 5.0

bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 1.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController"

behavior_server:
  ros__parameters:
    use_sim_time: true
    behavior_plugins: ["Spin", "Backup", "DriveOnHeading"]
    Spin:
      plugin: "nav2_behaviors/Spin"
    Backup:
      plugin: "nav2_behaviors/BackUp"
    DriveOnHeading:
      plugin: "nav2_behaviors/DriveOnHeading"

velocity_smoother:
  ros__parameters:
    use_sim_time: true
    smoothing_frequency: 20.0

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      robot_radius: 0.16
      resolution: 0.05
      footprint: "[[0.16, 0.16], [0.16, -0.16], [-0.16, -0.16], [-0.16, 0.16]]"
      plugins: ["voxel_layer", "inflation_layer"]
      voxel_layer:
        plugin: "nav2_costmap_2d/VoxelLayer"
        enabled: true
      inflation_layer:
        plugin: "nav2_costmap_2d/InflationLayer"
        inflation_radius: 0.55

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      robot_radius: 0.16
      resolution: 0.05
      footprint: "[[0.16, 0.16], [0.16, -0.16], [-0.16, -0.16], [-0.16, 0.16]]"
      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d/StaticLayer"
      inflation_layer:
        plugin: "nav2_costmap_2d/InflationLayer"
        inflation_radius: 0.55

# slam_toolbox:
#   ros__parameters:
#     use_sim_time: true
#     mode: "sync"